---
title: "Applications"
---

### Support sampling designs and implementation

-   **oNFI: Optimize national forest inventory design**

    Provides indicative optimal sample size and plot design for forest inventories based on biomass maps or variance models and a minimalist series of action timers (driving to plot, measuring trees, etc.).

    -   Online version: [link](URL)
    -   Local installation (R console): `devtools::instal_github("openforis/oNFI")`

-   **Bootstrap NFI sampling size (package name TBD)**

    Lauri's app currently on openforis shinyapps.io

-   **NFI implementation dashboard (package name TBD)**

    Simple app showing plot location and data collection status for tracking progress and management purposes.

### Support calculations from raw data

-   **SPvalid: Species names validation tool**

-   **Height-diameter models**

-   **MCredd: Monte Carlo uncertainty propagation for REDD+**
  
    MCredd guides users to organize data in a template in order to run MonteCarlo simulations for estimating the uncertainty of REDD+ greenhouse gas emissions and removals from forest changes.
    
    - Online version: [link](https://gaelsola.shinyapps.io/MCredd/) 
    - Local installation:
    `devtools::install_github("gaelso/MCredd")`
    `MCredd::shiny_run_MCredd()`
    
